### ISSUE TITLE
deploy gitbook

### ISSUE THREAD

**Issue by hayeah** [qtumproject/documents#3]
1. repo admin needs to enable github pages

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

2. configure CNAME to point to https://qtumproject.github.io/documents

https://help.github.com/articles/quick-start-setting-up-a-custom-domain/

**Comment by mikehash** [comment]
Done, please see docs.qtum.org

**Comment by mahuaibo** [comment]
👍
